---
- name: Configure hosts security
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Include variables from normal_setup
      ansible.builtin.include_vars:
        file: "../inventory/group_vars/normal_setup.yaml"
        name: normal_vars

    - name: Configure sudoers (NOPASSWD, disable admin, remove includes)
      block:
        - name: Block extra configs
          ansible.builtin.replace:
            path: /etc/sudoers
            regexp: '^@(includedir\s+/etc/sudoers.d)'
            replace: '#\1'
        - name: Block sudo for admin group
          ansible.builtin.replace:
            path: /etc/sudoers
            regexp: '^(%admin\s+ALL=\(ALL\)\s+ALL)'
            replace: '#\1'
        - name: Enable NOPASSWD for sudo group
          ansible.builtin.replace:
            path: /etc/sudoers
            regexp: '^(%sudo\s+ALL=\(ALL:ALL\)\s+)(ALL)'
            replace: '\1NOPASSWD:\2'

    - name: Disable root login shell
      ansible.builtin.replace:
        path: /etc/passwd
        regexp: '^root:([^:]*:){6}/bin/bash'
        replace: 'root:\1/usr/sbin/nologin'

    - name: Confgure /etc/ssh/sshd_config
      block:
        - name: Change ssh default port
          ansible.builtin.lineinfile:
            path: /etc/ssh/sshd_config
            regexp: '^#?Port '
            line: "Port {{ normal_vars.ansible_port }}"
        - name: Disable root login
          ansible.builtin.lineinfile:
            path: /etc/ssh/sshd_config
            regexp: '^#?PermitRootLogin '
            line: 'PermitRootLogin no'
        - name: Disable password authentication
          ansible.builtin.lineinfile:
            path: /etc/ssh/sshd_config
            regexp: '^#?PasswordAuthentication '
            line: 'PasswordAuthentication no'
        - name: Disable empty passwords
          ansible.builtin.lineinfile:
            path: /etc/ssh/sshd_config
            regexp: '^#?PermitEmptyPasswords '
            line: 'PermitEmptyPasswords no'
        - name: Enforce public key authentication
          ansible.builtin.lineinfile:
            path: /etc/ssh/sshd_config
            regexp: '^#?PubkeyAuthentication '
            line: 'PubkeyAuthentication yes'

    - name: Restart SSH
      block:
        - name: Reload systemd daemon
          ansible.builtin.systemd:
            daemon_reload: true
        - name: Restart SSH socket and service
          ansible.builtin.systemd:
            name: "{{ item }}"
            state: restarted
          loop:
            - ssh.socket
            - ssh.service

    - name: Update Ansible connection to normal port and user
      ansible.builtin.set_fact:
        ansible_port: "{{ normal_vars.ansible_port }}"
        ansible_user: "{{ normal_vars.ansible_user }}"
        ansible_ssh_private_key_file: "{{ normal_vars.ansible_ssh_private_key_file }}"
        ansible_become: true

    - name: Verify connection on new port as {{ ansible_user }}
      become: false
      block:
        - name: Wait for SSH on new port
          delegate_to: localhost
          ansible.builtin.wait_for:
            host: "{{ ansible_host }}"
            port: "{{ ansible_port }}"
            delay: 5
            timeout: 60
            state: started
        - name: Check connection to host
          delegate_to: localhost
          ansible.builtin.command: >
            ssh -i {{ ansible_ssh_private_key_file }}
            -p {{ ansible_port }}
            {{ ansible_user }}@{{ ansible_host }}
            "echo Connection successful"
          register: ssh_check
          changed_when: false
          failed_when: ssh_check.rc != 0

    - name: Install UFW and Fail2ban
      ansible.builtin.apt:
        name:
          - ufw
          - fail2ban
        state: present
        update_cache: true

    - name: Configure UFW firewall
      block:
        - name: Set default incoming policy to deny # noqa syntax-check[unknown-module]
          community.general.ufw:
            direction: incoming
            policy: deny

        - name: Set default outgoing policy to allow
          community.general.ufw:
            direction: outgoing
            policy: allow

        - name: Allow SSH on custom port
          community.general.ufw:
            rule: allow
            port: "{{ normal_vars.ansible_port }}"
            proto: tcp

        - name: Enable UFW
          community.general.ufw:
            state: enabled

    - name: Minimal host security configured
      ansible.builtin.debug:
        msg: |
          ✅ Security successfuly configured!
