---
- name: Start setup
  hosts: all
  become: false
  gather_facts: false
  tasks:
    - name: Start
      ansible.builtin.debug:
        msg: |
          ⚙️ Starting server setup...

- name: Update system
  ansible.builtin.import_playbook: "./manage_software/update.yaml"

- name: Add normal user
  ansible.builtin.import_playbook: "./manage_users/add_user.yaml"

- name: Configure security
  ansible.builtin.import_playbook: "./manage_software/security.yaml"

- name: Finish setup
  hosts: all
  become: false
  gather_facts: false
  tasks:
    - name: Print msg
      ansible.builtin.debug:
        msg: |
          ✅ Server setup was successful!
          Now you can connect to server via:
          ssh -i {{ ans_ssh_private_key }} -p {{ ans_normal_port }} {{ ans_normal_user }}@{{ ans_vps_host }}
