---
- name: Server setup - start
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Update and upgrade system
      block:
        - name: Apt first update
          ansible.builtin.apt:
            update_cache: true
            upgrade: dist

        - name: Ask whether to reboot server now
          ansible.builtin.pause:
            prompt: "Reboot server after upgrade? (yes/no) [yes]"
          register: reboot_answer

        - name: Set reboot decision with default
          ansible.builtin.set_fact:
            reboot_server: "{{ reboot_answer.user_input | default('yes') | lower }}"

        - name: System reboot
          when: reboot_answer.user_input | lower == "yes"
          ansible.builtin.reboot:
            msg: "Reboot after upgrade"
            connect_timeout: 5
            reboot_timeout: 600
            test_command: whoami

- import_playbook: user_setup.yaml
- import_playbook: security_setup.yaml

- name: Server setup - finish
  hosts: all
  tasks:
    - ansible.builtin.debug:
        msg: "✅ Server setup was successful!
          Now you can connect to server via:
          ssh -i {{ ansible_ssh_private_key_file }} -p {{ ansible_port }} {{ ansible_user }}@{{ ansible_host }}"
